# Generated by Django 3.2.7 on 2021-10-08 05:58

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokerboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('estimate_type', models.PositiveSmallIntegerField(choices=[(1, 'Series'), (2, 'Even'), (3, 'Odd'), (4, 'Fibonacci'), (5, 'Custom')], default=1, help_text='Estimation type')),
                ('title', models.CharField(help_text='Name of Pokerboard', max_length=20, unique=True)),
                ('description', models.CharField(blank=True, help_text='Description', max_length=100, null=True)),
                ('timer', models.PositiveIntegerField(help_text='Duration for voting (in seconds)')),
                ('estimation_cards', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), help_text='Array of estimation values choosed by user', size=None)),
                ('manager', models.ForeignKey(help_text='Creator of Pokerboard', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ticket_id', models.SlugField(help_text='Ticket ID imported from JIRA')),
                ('estimate', models.PositiveIntegerField(help_text='Final estimate of ticket', null=True)),
                ('order', models.PositiveIntegerField(help_text='Order of displaying of tickets')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Untouched'), (2, 'Ongoing'), (3, 'Estimated'), (4, 'Skipped')], default=1, help_text='Status of ticket')),
                ('start_datetime', models.DateTimeField(null=True)),
                ('end_datetime', models.DateTimeField(null=True)),
                ('pokerboard', models.ForeignKey(help_text='Pokerboard to which ticket belongs', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to='pokerboard.pokerboard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTicketEstimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('estimate', models.PositiveIntegerField(help_text='Final estimate of ticket')),
                ('estimation_time', models.PositiveIntegerField(help_text='Time taken by user to estimate (in seconds)')),
                ('ticket_id', models.ForeignKey(help_text='Ticket ID on database', on_delete=django.db.models.deletion.CASCADE, related_name='estimations', to='pokerboard.ticket')),
                ('user', models.ForeignKey(help_text='Person estimated', on_delete=django.db.models.deletion.CASCADE, related_name='estimations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PokerboardUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Spectator'), (2, 'Contributor')], default=2, help_text='Role')),
                ('pokerboard', models.ForeignKey(help_text='Pokerboards Associated', on_delete=django.db.models.deletion.CASCADE, to='pokerboard.pokerboard')),
                ('user', models.ForeignKey(help_text='Users Associated', on_delete=django.db.models.deletion.CASCADE, related_name='pokerboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PokerboardGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Spectator'), (2, 'Contributor')], default=2, help_text='Role')),
                ('group', models.ForeignKey(help_text='Groups Associated', on_delete=django.db.models.deletion.CASCADE, to='group.group')),
                ('pokerboard', models.ForeignKey(help_text='Pokerboards Associated', on_delete=django.db.models.deletion.CASCADE, to='pokerboard.pokerboard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, help_text='Non existing user email', max_length=254, null=True)),
                ('is_accepted', models.BooleanField(default=False, help_text='Indicates if invitation accepted or not')),
                ('group', models.ForeignKey(blank=True, help_text='Group Invited', null=True, on_delete=django.db.models.deletion.CASCADE, to='group.group')),
                ('pokerboard', models.ForeignKey(help_text='Pokerboard', on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='pokerboard.pokerboard')),
                ('user', models.ForeignKey(blank=True, help_text='Person invited', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
