# Generated by Django 2.2 on 2021-10-05 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokerboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0002_auto_20211005_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='userticketestimate',
            name='user',
            field=models.ForeignKey(help_text='Person estimated', on_delete=django.db.models.deletion.DO_NOTHING, related_name='estimations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='pokerboard',
            field=models.ForeignKey(help_text='Pokerboard to which ticket belongs', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to='pokerboard.Pokerboard'),
        ),
        migrations.AddField(
            model_name='pokerboarduser',
            name='pokerboard',
            field=models.ForeignKey(help_text='Pokerboards Associated', on_delete=django.db.models.deletion.DO_NOTHING, to='pokerboard.Pokerboard'),
        ),
        migrations.AddField(
            model_name='pokerboarduser',
            name='user',
            field=models.ForeignKey(help_text='Users Associated', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pokerboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pokerboardgroup',
            name='group',
            field=models.ForeignKey(help_text='Groups Associated', on_delete=django.db.models.deletion.DO_NOTHING, to='group.Group'),
        ),
        migrations.AddField(
            model_name='pokerboardgroup',
            name='pokerboard',
            field=models.ForeignKey(help_text='Pokerboards Associated', on_delete=django.db.models.deletion.DO_NOTHING, to='pokerboard.Pokerboard'),
        ),
        migrations.AddField(
            model_name='pokerboard',
            name='manager',
            field=models.ForeignKey(help_text='Creator of Pokerboard', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invites',
            name='group',
            field=models.ForeignKey(help_text='Group Invited', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='group.Group'),
        ),
        migrations.AddField(
            model_name='invites',
            name='pokerboard',
            field=models.ForeignKey(help_text='Pokerboard', on_delete=django.db.models.deletion.DO_NOTHING, related_name='invites', to='pokerboard.Pokerboard'),
        ),
        migrations.AddField(
            model_name='invites',
            name='user',
            field=models.ForeignKey(help_text='Person invited', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invites', to=settings.AUTH_USER_MODEL),
        ),
    ]
