# Generated by Django 2.2 on 2021-10-21 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0002_auto_20211021_0717'),
        ('pokerboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userticketestimate',
            name='user',
            field=models.ForeignKey(help_text='Person estimated', on_delete=django.db.models.deletion.CASCADE, related_name='estimations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='pokerboard',
            field=models.ForeignKey(help_text='Pokerboard to which ticket belongs', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to='pokerboard.Pokerboard'),
        ),
        migrations.AddField(
            model_name='pokerboarduser',
            name='pokerboard',
            field=models.ForeignKey(help_text='Pokerboards Associated', on_delete=django.db.models.deletion.CASCADE, to='pokerboard.Pokerboard'),
        ),
        migrations.AddField(
            model_name='pokerboarduser',
            name='user',
            field=models.ForeignKey(help_text='Users Associated', on_delete=django.db.models.deletion.CASCADE, related_name='pokerboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pokerboardgroup',
            name='group',
            field=models.ForeignKey(help_text='Groups Associated', on_delete=django.db.models.deletion.CASCADE, to='group.Group'),
        ),
        migrations.AddField(
            model_name='pokerboardgroup',
            name='pokerboard',
            field=models.ForeignKey(help_text='Pokerboards Associated', on_delete=django.db.models.deletion.CASCADE, to='pokerboard.Pokerboard'),
        ),
        migrations.AddField(
            model_name='pokerboard',
            name='manager',
            field=models.ForeignKey(help_text='Creator of Pokerboard', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='managercredentials',
            name='user',
            field=models.OneToOneField(help_text="Manager's details", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invite',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Group Invited', null=True, on_delete=django.db.models.deletion.CASCADE, to='group.Group'),
        ),
        migrations.AddField(
            model_name='invite',
            name='pokerboard',
            field=models.ForeignKey(help_text='Pokerboard', on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='pokerboard.Pokerboard'),
        ),
        migrations.AddField(
            model_name='invite',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Person invited', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to=settings.AUTH_USER_MODEL),
        ),
    ]
