# Generated by Django 2.2 on 2021-10-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerboard', '0002_auto_20211020_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='managercredentials',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
