# Generated by Django 2.2 on 2021-10-20 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokerboard', '0002_auto_20211007_0733'),
        ('pokerboard', '0002_auto_20211009_0413'),
    ]

    operations = [
    ]
