# Generated by Django 2.2 on 2021-10-06 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0003_auto_20211006_1447'),
        ('pokerboard', '0002_auto_20211005_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(help_text='Non existing user email', max_length=254, null=True)),
                ('is_accepted', models.BooleanField(default=False, help_text='Indicates if invitation accepted or not')),
                ('group', models.ForeignKey(help_text='Group Invited', null=True, on_delete=django.db.models.deletion.CASCADE, to='group.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='pokerboard',
            name='isDeleted',
        ),
        migrations.RemoveField(
            model_name='pokerboardgroup',
            name='isDeleted',
        ),
        migrations.RemoveField(
            model_name='pokerboarduser',
            name='isDeleted',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='isDeleted',
        ),
        migrations.AddField(
            model_name='pokerboard',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokerboardgroup',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokerboarduser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userticketestimate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userticketestimate',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userticketestimate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pokerboard',
            name='description',
            field=models.CharField(blank=True, help_text='Description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pokerboard',
            name='estimate_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Series'), (2, 'Even'), (3, 'Odd'), (4, 'Fibonacci'), (5, 'Custom')], default=1, help_text='Estimation type'),
        ),
        migrations.AlterField(
            model_name='pokerboard',
            name='manager',
            field=models.ForeignKey(help_text='Creator of Pokerboard', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pokerboardgroup',
            name='group',
            field=models.ForeignKey(help_text='Groups Associated', on_delete=django.db.models.deletion.CASCADE, to='group.Group'),
        ),
        migrations.AlterField(
            model_name='pokerboardgroup',
            name='pokerboard',
            field=models.ForeignKey(help_text='Pokerboards Associated', on_delete=django.db.models.deletion.CASCADE, to='pokerboard.Pokerboard'),
        ),
        migrations.AlterField(
            model_name='pokerboarduser',
            name='pokerboard',
            field=models.ForeignKey(help_text='Pokerboards Associated', on_delete=django.db.models.deletion.CASCADE, to='pokerboard.Pokerboard'),
        ),
        migrations.AlterField(
            model_name='pokerboarduser',
            name='user',
            field=models.ForeignKey(help_text='Users Associated', on_delete=django.db.models.deletion.CASCADE, related_name='pokerboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userticketestimate',
            name='ticket_id',
            field=models.ForeignKey(help_text='Ticket ID on database', on_delete=django.db.models.deletion.CASCADE, related_name='estimations', to='pokerboard.Ticket'),
        ),
        migrations.AlterField(
            model_name='userticketestimate',
            name='user',
            field=models.ForeignKey(help_text='Person estimated', on_delete=django.db.models.deletion.CASCADE, related_name='estimations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Invites',
        ),
        migrations.AddField(
            model_name='invite',
            name='pokerboard',
            field=models.ForeignKey(help_text='Pokerboard', on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='pokerboard.Pokerboard'),
        ),
        migrations.AddField(
            model_name='invite',
            name='user',
            field=models.ForeignKey(help_text='Person invited', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to=settings.AUTH_USER_MODEL),
        ),
    ]
