# Generated by Django 2.2 on 2021-10-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerboard', '0002_auto_20211005_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokerboard',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
