# Generated by Django 2.2 on 2021-10-19 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pokerboard', '0002_auto_20211009_0413'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.EmailField(help_text='Jira Username', max_length=254)),
                ('password', models.CharField(help_text='Jira Password or Token', max_length=250)),
                ('url', models.URLField(help_text="User's Jira Url")),
                ('user', models.OneToOneField(help_text="Manager's details", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
