# Generated by Django 2.2 on 2021-10-25 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokerboard', '0002_auto_20211025_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokerboarduser',
            name='group',
            field=models.ForeignKey(help_text='Groups Associated', null=True, on_delete=django.db.models.deletion.CASCADE, to='group.Group'),
        ),
    ]
