# Generated by Django 2.2 on 2021-10-06 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokerboard', '0003_auto_20211006_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='email',
            field=models.EmailField(blank=True, default=None, help_text='Non existing user email', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invite',
            name='group',
            field=models.ForeignKey(blank=True, default=None, help_text='Group Invited', on_delete=django.db.models.deletion.CASCADE, to='group.Group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invite',
            name='user',
            field=models.ForeignKey(blank=True, default=None, help_text='Person invited', on_delete=django.db.models.deletion.CASCADE, related_name='invites', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
