# Generated by Django 2.2 on 2021-10-20 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokerboard', '0003_merge_20211020_1356'),
        ('pokerboard', '0002_auto_20211019_0834'),
    ]

    operations = [
    ]
