# Generated by Django 2.2 on 2021-10-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerboard', '0004_auto_20211025_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
