# Generated by Django 2.2 on 2021-10-06 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokerboard', '0004_auto_20211006_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='email',
            field=models.EmailField(blank=True, help_text='Non existing user email', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Group Invited', null=True, on_delete=django.db.models.deletion.CASCADE, to='group.Group'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Person invited', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to=settings.AUTH_USER_MODEL),
        ),
    ]
