# Generated by Django 2.2 on 2021-10-27 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokerboard', '0003_managercredentials_deleted_at'),
        ('pokerboard', '0005_auto_20211026_1826'),
    ]

    operations = [
    ]
