# Generated by Django 2.2 on 2021-10-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokerboard', '0003_auto_20211021_1003'),
        ('pokerboard', '0006_merge_20211027_1335'),
    ]

    operations = [
    ]
