# Generated by Django 2.2 on 2021-10-28 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokerboard', '0007_merge_20211027_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Accepted'), (0, 'Pending'), (2, 'Declined')], default=0, help_text='Indicates if invitation accepted or not'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='user',
            field=models.ForeignKey(default=None, help_text='Person invited', on_delete=django.db.models.deletion.CASCADE, related_name='invites', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
