# Generated by Django 2.2 on 2021-11-08 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pokerboard', '0008_auto_20211028_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userticketestimate',
            name='estimation_time',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Time taken by user to estimate (in seconds)'),
        ),
        migrations.AlterUniqueTogether(
            name='userticketestimate',
            unique_together={('user', 'ticket_id')},
        ),
    ]
